"""add year

Revision ID: 23d7c113bf4e
Revises: 7dabd820c9e9
Create Date: 2023-03-23 17:42:04.306057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d7c113bf4e'
down_revision = '7dabd820c9e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottles', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bottles', 'year')
    # ### end Alembic commands ###
