"""initial migration

Revision ID: 2badcc785389
Revises: 
Create Date: 2023-03-30 09:41:31.817214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2badcc785389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wineries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bottles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('grape_id', sa.Integer(), nullable=True),
    sa.Column('winery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grape_id'], ['grapes.id'], ),
    sa.ForeignKeyConstraint(['winery_id'], ['wineries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bottles')
    op.drop_table('wineries')
    op.drop_table('grapes')
    # ### end Alembic commands ###
